### ISSUE TITLE
Newer open source project

### ISSUE THREAD

**Issue by larsnaesbye** [rokubun/gnss_tools#3]
Hi, have you considered looking at the toolbox in hasty development over at https://github.com/gwbres/rinex ? Some of the functionality might either complement or replace the older non-open source tools in the image.

**Comment by alexlopezc** [comment]
Hi, apologies for the delay in the response.

It looks interesting and we will consider it. We don't use some of the tools anymore since we have our own converter written in C, but we'll take a look.

Thank you for the suggestion!
